Improve devtools panel filters
duckduckgo/duckduckgo-privacy-extension pull request #1311
Opened 2022-08-05 10:00 UTC by GuiltyDolphin

**Reviewer:** @jonathanKingston 

## Description:

This:
- adds support for filtering requests on URL
- adds support for hiding _only_ 1P requests
- fixes cookie rows not being hidden by toggle

## Steps to test this PR:

Test search filter:

1. Open http://privacy-test-pages.glitch.me/privacy-protections/request-blocking/ ("the site")
2. Open devtools panel, set target to the opened site
3. On the site, click "Start the test"
4. Switch back to the panel
5. A bunch of requests should show (about 19)
6. In the filter box, type "img" and hit enter
7. One request should now show
8. Empty the filter box and hit enter
9. All previous requests should now show

Test 1P filter:

1. Open https://www.tumblr.com/explore/trending
2. Open the devpanel and set target to opened site
3. You should see some 1P requests and some blocked requests
4. On one of the blocked requests (e.g., `id5-sync.com/g/v2/102.json`) hit the "I" to the left of the request and hit "Reload page" at the top
5. You should now see some ignored 1P requests and ignored 3P requests (and some blocked requests)
6. Untick the "Ignored (1P)" filter
7. You should see some ignored and blocked requests, but all the 1P ignored requests should be hidden
8. Tick the "Ignored (1P)" filter - now all the ignored requests should be visible again
9. Untick the "Ignored" filter
10. No ignored requests should be visible
11. Untick the "Ignored (1P)" filter
12. Nothing should change
13. Tick the "Ignored" filter
14. Now only 1P ignored requests should show out of all the ignores

Test HTTP Cookie filter:

1. Navigate to http://privacy-test-pages.glitch.me/privacy-protections/storage-blocking/ (the site)
2. Open devpanel and set target to the site
3. Go back to the site and click "Store data"
4. In the devpanel you should see some requests with action `🍪 block`
5. Untick the HTTP Cookies filter
6. The `🍪 block` requests should vanish
7. Tick the HTTP Cookies filter
8. The `🍪 block` requests should reappear

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

2022-12-19 13:50 UTC, GuiltyDolphin commented
@sammacbeth would you be able to review?

Note that the cookie fix doesn't appear to do anything anymore, but this seems unrelated to this PR. For kbb.com/whats-my-car-worth, I'm not seeing the HTTP cookies on `develop`, but am seeing them on `2022.12.12`.

2022-12-20 11:32 UTC, sammacbeth requested changes

2022-12-20 11:32 UTC, sammacbeth commented on shared/js/devtools/panel.es6.js
> +        return panelConfig.rowVisibility.cookieHTTP
You should include set cookies here.
```suggestion
    case 'cookie-tracker':
    case 'set-cookie-tracker':
        return panelConfig.rowVisibility.cookieHTTP
```

2022-12-20 11:32 UTC, sammacbeth commented on shared/js/devtools/panel.es6.js
> +    }
Maybe add a 'default' or just a `return true` do this function always returns a boolean instead of `undefined`.

2022-12-21 10:00 UTC, GuiltyDolphin commented
@sammacbeth have applied the changes

2022-12-21 12:43 UTC, sammacbeth approved these changes

2022-12-21 12:43 UTC, merged