Add ddg2dnr as a sub-package
duckduckgo/duckduckgo-privacy-extension pull request #1806
Opened 2023-03-20 08:07 UTC by sammacbeth

Merges https://github.com/duckduckgo/ddg2dnr as a subproject of this repo.

2023-03-20 09:13 UTC, shakyShane requested changes

2023-03-20 09:13 UTC, shakyShane commented on packages/ddg2dnr/tsconfig.json
@sammacbeth  I would double-check that the Typescript setup is working as you expect. 

There tends to be 2 paths to go down during a migration like this

1) You can exclude type-checking the `packages/` part from the root tsconfig.json, and then ensure that `tsc` is also run for the workspace

or 

2) You configure the root-level tsconfig to also check child packages (via regular `include: ['...']`)

The reason I mention this, is that from the current PR I don't think the child `tsconfig.json` will work exactly as you imagine (eg: it's rules won't override the top level ones).

--

A 3rd option, which might not make sense here, is to use the recommended 'project references' setup, but that brings a whole heap of other issues too, like needing to compile `.d.ts` files for each project etc. (I've just beedn down this rabbit hole)

2023-03-21 14:29 UTC, kzar approved these changes

2023-03-21 15:16 UTC, shakyShane requested changes

2023-03-21 15:16 UTC, shakyShane commented on packages/ddg2dnr/tsconfig.json
> +  ]
This is incorrect (should be inside compilerOptions) - but actually it's not needed at all - TS will auto-include npm dependencies that are in `node_modules`
```suggestion
```

2023-03-21 15:16 UTC, shakyShane commented on tsconfig.json
>          "chrome"
as before, types: ["chrome"] can be removed

2023-03-21 15:16 UTC, shakyShane commented on packages/ddg2dnr/tsconfig.json
> +  },
```suggestion
  "extends": "../../tsconfig.json",
```

2023-03-21 15:17 UTC, shakyShane commented on packages/ddg2dnr/tsconfig.json
> +  },
@sammacbeth we can discourage config drift by sharing the compilerOptions from the root

2023-03-21 15:18 UTC, shakyShane commented on packages/ddg2dnr/tsconfig.json
> +  ]
@sammacbeth Sorry if this wasn't part of the PR, but we might as well fix now :)

2023-03-21 17:23 UTC, shakyShane approved these changes

2023-03-21 18:20 UTC, merged