Update AMP protection with strict http checking
duckduckgo/duckduckgo-privacy-extension pull request #2206
Opened 2023-08-23 14:14 UTC by SlayterDev

**Reviewer:** @jonathanKingston 

## Description:

See https://app.asana.com/0/414235014887631/1205292391529323/f for context.

This PR enforces strict checking for http links in AMP protection. Deep extraction has been updated to check if the extracted link is http and discards it otherwise. However deep extraction is currently disabled in the extension. I've made the same update to the simple link extraction case for google.com domains. For instance https://www.google.com/amp/s/javascript://example.com should redirect to a 404 page.

## Steps to test this PR:
1. Smoke test this page: https://privacy-test-pages.glitch.me/privacy-protections/amp/
2. Check https://privacy-test-pages.glitch.me/privacy-protections/amp/ redirects to a 404 page.

## Automated tests:
- [ ] Unit tests
- [ ] Integration tests

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR Author Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications

2023-08-23 14:45 UTC, jonathanKingston requested changes

2023-08-23 14:45 UTC, jonathanKingston commented on shared/js/background/amp-protection.js
> +            if (newUrl.match(/^.+:\/\//) && !newUrl.startsWith('http')) {
Can you pass to the URL constructor and check scheme (also catching the potential throw for relative paths)

2023-08-23 14:45 UTC, jonathanKingston commented on shared/js/background/amp-protection.js
> +            const newSite = new Site(newUrl.startsWith('http') ? newUrl : `https://${newUrl}`)
Is this needed if we exit early for non http and relative paths?

2023-08-23 15:37 UTC, SlayterDev commented on shared/js/background/amp-protection.js
> +            const newUrl = match[1]
Just URL extraction

2023-08-23 15:54 UTC, jonathanKingston commented on shared/js/background/amp-protection.js
> +                } catch (e) {
You don't need e here at all for either
```suggestion
                } catch {
```

2023-08-23 23:22 UTC, jonathanKingston approved these changes

2023-08-24 14:31 UTC, jonathanKingston commented on shared/js/background/amp-protection.js
> +            console.log(targetUrl)
```suggestion
```

2023-08-24 14:34 UTC, jonathanKingston commented on shared/js/background/amp-protection.js
> +                    const newUrl = new URL(`https://${targetUrl}`)
This control flow is a little weird but I can't think of a better way.

I wonder if making it clear in a comment that the throw from the constructor here is important in validating the URL?

2023-08-24 15:26 UTC, merged