Stop UA from attempting to rotate (disabled already)
duckduckgo/duckduckgo-privacy-extension pull request #569
Opened 2021-03-16 12:29 UTC by Charlie-belmer

Stop User Agent rotations from occurring. The UA spoofing is already disabled, this just stops support code from executing until all UA fixes are implemented.

2021-03-16 12:40 UTC, jonathanKingston approved these changes

2021-03-16 17:26 UTC, dharb requested changes
Thanks for doing this @Charlie-belmer. Looks like the linter is hollering about unreachable code now. You should be able to silence it by either commenting out the remainder of these methods after returning, or by adding `/* eslint-disable no-unreachable */` to the top of this file.

2021-03-24 09:09 UTC, sammacbeth reviewed
Tbh I'd rather the code was removed rather than leaving a load of commented code in. When we want to restore the old code we can just revert this PR to undo the code deletion.

2021-04-08 13:40 UTC, Charlie-belmer commented
Closing this in favor of PR #593

2021-04-08 13:40 UTC, closed without merging